title: "envyen"
baseurl: "/"
description: envyen.com
theme: just-the-docs
permalink: pretty
heading_anchors: true

url: https://envyen.com

aux_links:
  "about":
    - "//envyen.com/about"

collections:
  posts:
    permalink: "/:collection/:path/"
    output: true
  oss:
    permalink: "/:collection/:path/"
    output: true
  tutorials:
    permalink: "/:collection/:path/"
    output: true
  tags:
    output: true
    permalink: "tags/:path/"