title: "envyen"
baseurl: "/"
remote_theme: pmarsceill/just-the-docs
permalink: pretty

heading_anchors: true

# Enable or disable the site search
search_enabled: false

# Set the search token separator for hyphenated-word search:
search_tokenizer_separator: /[\s/]+/


plugins:
  - jekyll-gist
  - jekyll-seo-tag

collections:
  posts:
    permalink: "/:collection/:path/"
    output: true
  oss:
    permalink: "/:collection/:path/"
    output: true
  tutorials:
    permalink: "/:collection/:path/"
    output: true
  tags:
    output: true
    permalink: "tags/:path/"

#just_the_docs:
#  collections:
#    posts:
#      name: posts
#    oss:
#      name: open-source
#    tutorials:
#      name: tutorials
