title: "envyen"
baseurl: "/"
remote_theme: pmarsceill/just-the-docs
permalink: pretty

heading_anchors: true




# Enable or disable the site search
# Supports true (default) or false
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 6
  # Maximum amount of previews per search result
  # Default: 3
  previews: 2
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 3
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false





# Aux links for the upper right navigation
aux_links:
  "code":
    - "//github.com/envyen"
  "about":
    - "//envyen.com/about"


plugins:
  - jekyll-gist
  - jekyll-seo-tag

collections:
  posts:
    permalink: "/:collection/:path/"
    output: true
  oss:
    permalink: "/:collection/:path/"
    output: true
  tutorials:
    permalink: "/:collection/:path/"
    output: true
  tags:
    output: true
    permalink: "tags/:path/"

#just_the_docs:
#  collections:
#    posts:
#      name: posts
#    oss:
#      name: open-source
#    tutorials:
#      name: tutorials

staticman_Url: https://env-comment.herokuapp.com/v2/entry/envyen/docs/gh-pages/comments

reCaptcha:
  siteKey: 6LeyhdEaAAAAAMAn_noABL-5OCZrQNejdHtjK9Pq
  secret:  "kY0FQlCNnF8R++4g4ZiJyHSI7gWjnxX6lolVehD8ImYlGEvNXWqH4euAhLMbtJIB2d68CwtZMWq3tiQpW3m6b6FY6rdgFgpUiiTgsV0cr87I8vSDB/9rHrkgFqKzxClDhXy5Ck8XAxOD1ZF59vPihjv/pMecV+a6uf89P73vnz0D8PBuID+oPXVxkOBdqiT9xZHJXgbezOECevEs0YwZqEP5mbz0wXEZlbGqPUmAml/CZD9ffz3pWYipZE7IpNDJsYa+2Both4OOJvzx56Jgte7Gqy6TvqTXn9LdanromruEqJ5luDLuN+UOXn92B4hw+cXh4Qr/Y4N8qRc7CF1CigmKhE15c+jqKsnaTnT2hYNZAR3oEowlmOGr/6OCjtVwvpbCLSaR/EXHipJdHV/AvB9P7uAFiBiUZ6CYibQ3bIEwBGsnJhFxeu0jv9ODVgXn+avPXOArZD+yHlIFiRf2IC6YfZV1QGgZpi7lMi48jIbdWi5WFSjjNkTnwKDKwMu8Qx22Dh4JFXJxEhRoBNqylZ8QtQ/AEXpgWHTfMX1qUHMPm4o/IjD8EoesDCMH67b2VsvItQVJTDbsiJK2rweJ72GtHAiyfZ1LO5KVNOCOcHUdtrP6Mt/6zHY5WJVIYYBgHKh8nZ00OISoBFpC7+UYdOawo/C3khkU/O0Dx25b08c="



